baseURL = "https://pwm-teach.github.io/morton-teaches/"
languageCode = "en-gb"
title = "Morton Teaches"
theme = "PaperMod"
paginate = 10

[params]
  showPostNavLinks = true
  showReadingTime = true
  showToc = true

[outputs]
  [outputs.home]
    output = ["HTML", "RSS", "JSON"]
